#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /c/Users/userGraceNguyen/Documents/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: chess

depend: chess-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.chess $(@)

.PHONY: chess
chess:
	@$(MAKE) -f Makefile.chess all

.PHONY: chess-depend
chess-depend:
	@$(MAKE) -f Makefile.chess depend

project_name_list:
	@echo chess
